### ISSUE TITLE
How do I use this from Pelias API?

### ISSUE THREAD

**Issue by tuukka** [pelias/transit#27]
Hi! I'm able to see the transit stops in Elastic Search but not via Pelias API searches. Are there any instructions or examples of how to use it or what to look for in the API configuration?

For more context, I'm currently researching which of the various GTFS import modules I should deploy, and have yet to find one that works end-to-end.

**Comment by missinglink** [comment]
Hi @tukka, if you can see them in elasticsearch then that means the importer is working, so that's good news.
Could you please post one document from elasticsearch so I can see what properties it has?

One thing I would try first is to [filter by source or layer](https://github.com/pelias/documentation/blob/master/search.md#filter-your-search), you should see the `source` and `layer` properties listed against the document in elasticsearch.

If that works for you then it would be helpful to post an example of the request you are sending to `pelias/api` and what response you are getting vs. what you're expecting to see.

**Comment by orangejulius** [comment]
This was probably fixed by https://github.com/pelias/api/pull/1316, before that the API did not actually know about all the possible source/layer options that might have been brought in by custom importers.

Let us know if this is still a problem.

**Comment by irbian** [comment]
I´m too having this problem

I see the data on the elasticsearch, but when checked on the API with /api/v1/search?text=mystopname&layers=stops 

I get

```
errors: [
"'stops' is an invalid layers parameter. Valid options: coarse,address,venue,street,country,macroregion,region,county,localadmin,locality,borough,neighbourhood,continent,empire,dependency,macrocounty,macrohood,microhood,disputed,postalcode,ocean,marinearea"
],
```

**Comment by missinglink** [comment]
since https://github.com/pelias/config/pull/127 Pelias will automatically discover all 'layers' and 'sources' from records which exist in elasticsearch.

please check that there is a document in your elasticsearch index which has the layer 'stops'.

If you're using the `pelias/docker` project there is a command named `pelias elastic stats` which can be used to query this information directly from elasticsearch.

Also worth checking all your Pelias code is relatively up-to-date (at least from this year).

If you're using the `pelias/docker` project there is a command named `pelias compose pull` which can be used to pull the latest docker images.

**Comment by irbian** [comment]
> If you're using the pelias/docker project there is a command named pelias elastic stats which can be used to query this information directly from elasticsearch.

This is very helpful :) this is what is showing:

```
       {
          "key" : "transit",
          "doc_count" : 26,
          "layers" : {
            "doc_count_error_upper_bound" : 0,
            "sum_other_doc_count" : 0,
            "buckets" : [
              {
                "key" : "stops",
                "doc_count" : 26
              }
            ]
          }
        }
```

> If you're using the pelias/docker project there is a command named pelias compose pull which can be used to pull the latest docker images.

Yeah, I have been working recently with this, using pelias/docker

**Comment by missinglink** [comment]
Okay then try setting `api.targets.auto_discover` to `true` in your `pelias.json` and restart the server.

**Comment by orangejulius** [comment]
The other trick that might be relevant is you have to restart the API if you have imported custom data since it started. It only detects the custom sources and layers on startup.

`pelias compose kill api && pelias compose up api` should do it for you.

**Comment by irbian** [comment]
What sorcery is this? it's working!

> Okay then try setting api.targets.auto_discover to true in your pelias.json and restart the server.

This was already setted before (even when auto_discover default value is true iirc)

> pelias compose kill api && pelias compose up api should do it for you.

What I don´t understand is that I´m sure I tried with a pelias compose down, pelias compose up before this. Maybe I didn´t do it this time but in a time before, with so much tests...

Thanks!
